#!/usr/bin/env node
const { program } = require('commander')
const { version, description } = require('./package.json')
const split = require('split')

program
.version(version)
.description(description)
.addHelpText('after', `
Examples:

  # Convert all a file
  cat some.ndjson | ndjson-2-json > some.json
  # which can also be written
  ndjson-2-json < some.ndjson > some.json

  # Convert just the 20 first lines
  head -n 20 some.ndjson | ndjson-2-json > 20_first_entries.json
`)
.parse(process.argv)

if (process.stdin.isTTY) program.help()

process.stdout.write('[')

let lastNonEmptyLine

process.stdin
.pipe(split())
.on('data', line => {
  if (line) {
    if (lastNonEmptyLine) process.stdout.write('\n  ' + lastNonEmptyLine + ',')
    lastNonEmptyLine = line
  }
})
.on('close', () => {
  if (lastNonEmptyLine) {
    process.stdout.write('\n  ' + lastNonEmptyLine + '\n')
  }
  process.stdout.write(']\n')
})

// Prevent logging an EPIPE error when piping the output
// cf https://github.com/maxlath/wikibase-cli/issues/7
process.stdout.on('error', err => {
  if (err.code === 'EPIPE') process.exit(0)
  else throw err
})
